require 'minitest/rails'
require 'minitest/unit'
require 'minitest/spec'
require 'minitest/matchers'
require 'minitest/rails/shoulda'
require 'minitest/given'
require 'minitest/benchmark'
# require 'minitest/hell'
require 'minitest/rails/capybara'

