# sendgrid
SENDGRID_USERNAME: app10941941@heroku.com
SENDGRID_PASSWORD: rfxvxkkg
ADMIN_NAME: HMFIC
ADMIN_EMAIL: fred.schoeneman@gmail.com
ADMIN_PASSWORD: password 

# facebook
FACEBOOK_APP_ID: 413345198769391
FACEBOOK_APP_SECRET: be286757de06881b6d8eb6e2afe9378c

# twitter 
TWITTER_CONSUMER_KEY: WYcumlaM4s0X2WH4vPUBKQ
TWITTER_CONSUMER_SECRET: 0CDtY2LwuobXN03ceaTePowzzBqFUJ4BsPdtRmt3ON4

# linkedin
LINKEDIN_CONSUMER_KEY: 0VhJKsgv3q8Qu0FU
LINKEDIN_CONSUMER_SECRET: 6c595d33-a563-4102-a352-6c0f0936c8f6

# Gplus
GPLUS_CLIENT_ID: 16145563248.apps.googleusercontent.com
GPLUS_KEY: 16145563248.apps.googleusercontent.com
GPLUS_SECRET: VrHL2ZHhZtZqTZgfDy9p_InR
GPLUS_API_KEY: AIzaSyADVTXkWUzmyp7wfLd1SBRNGeWDbBqBO3U

# Google api client
GOOGLE_API_KEY: AIzaSyDu8IFCALXESDHzBKfkGQDEkDjTQC2HfLk

# roles for rolify (not sure they need to be here)
ROLES: [admin, user, silver, gold, platinum, winery]

# stripe test keys
STRIPE_API_KEY_TEST: sk_test_raxRUHqGQrtOw2Zwd3FqasDq
STRIPE_PUBLIC_KEY_TEST: pk_test_g7r7v1PCKFef8DEqhu45N1Mn

# stripe live keys
STRIPE_API_KEY: sk_live_M52LCiFWrvPjTBSVSPlFVJ2n
STRIPE_PUBLIC_KEY: pk_live_KaCLbv37sQc5Ra9wJMEmqjAa

# linkedin authentication
# API Key:
# gjkaytzs7we5
# Secret Key:
# 0VhJKsgv3q8Qu0FU
# OAuth User Token:
# 8c8a8ca4-bb9e-43b5-9872-3e6e8793d309
# OAuth User Secret:
# 6c595d33-a563-4102-a352-6c0f0936c8f6


# gplus / google oauth2

# Client ID:  
# 16145563248.apps.googleusercontent.com
# Email address:  
# 16145563248@developer.gserviceaccount.com
# Client secret:  
# VrHL2ZHhZtZqTZgfDy9p_InR
# Redirect URIs:  https://localhost:3000/oauth2callback
# JavaScript origins: https://localhost:3000



#  information
# The following information is shown to users whenever you request access to their private data.
# Product name: Bloocher
# Google account: fred.schoeneman@gmail.com
# Home page URL:  bloocher.com
# Edit branding information...
# Client ID for web applications
# Client ID:  
# 16145563248.apps.googleusercontent.com
# Email address:  
# 16145563248@developer.gserviceaccount.com
# Client secret:  
# VrHL2ZHhZtZqTZgfDy9p_InR
# Redirect URIs:  http://localhost:3000/users/auth/gplus/callback
# JavaScript origins: https://localhost:3000