
development:
  adapter: postgresql
  encoding:
  database: bloocher_development
  pool: 5
  username: fred
  password: tastywave

test:
  adapter: postgresql
  encoding:
  database: bloocher_test
  pool: 5
  username:
  password:

