
development:
  adapter: postgresql
  encoding: unicode
  database: bloocher_development
  pool: 5
  timeout: 5000
  username: fred
  password: tastywave

test:
  adapter: postgresql
  encoding: unicode
  database: bloocher_test
  pool: 5
  timeout: 5000
  username: fred
  password: tastywave

