
development:
  adapter: postgresql
  encoding: unicode
  database: bloocher_development
  pool: 5
  username: frederick
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bloocher_test
  pool: 5
  username: frederick
  password: 

