
development:
  adapter: postgresql
  encoding: unicode
  database: bloocher_development
  pool: 5
  username: 
  password: tastywave

test:
  adapter: postgresql
  encoding: unicode
  database: bloocher_test
  pool: 5
  username: 
  password: tastywave

