require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VineyardsController do

  # This should return the minimal set of attributes required to create a valid
  # Vineyard. As you add validations to Vineyard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "producer_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VineyardsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vineyards as @vineyards" do
      vineyard = Vineyard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vineyards).should eq([vineyard])
    end
  end

  describe "GET show" do
    it "assigns the requested vineyard as @vineyard" do
      vineyard = Vineyard.create! valid_attributes
      get :show, {:id => vineyard.to_param}, valid_session
      assigns(:vineyard).should eq(vineyard)
    end
  end

  describe "GET new" do
    it "assigns a new vineyard as @vineyard" do
      get :new, {}, valid_session
      assigns(:vineyard).should be_a_new(Vineyard)
    end
  end

  describe "GET edit" do
    it "assigns the requested vineyard as @vineyard" do
      vineyard = Vineyard.create! valid_attributes
      get :edit, {:id => vineyard.to_param}, valid_session
      assigns(:vineyard).should eq(vineyard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vineyard" do
        expect {
          post :create, {:vineyard => valid_attributes}, valid_session
        }.to change(Vineyard, :count).by(1)
      end

      it "assigns a newly created vineyard as @vineyard" do
        post :create, {:vineyard => valid_attributes}, valid_session
        assigns(:vineyard).should be_a(Vineyard)
        assigns(:vineyard).should be_persisted
      end

      it "redirects to the created vineyard" do
        post :create, {:vineyard => valid_attributes}, valid_session
        response.should redirect_to(Vineyard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vineyard as @vineyard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vineyard.any_instance.stub(:save).and_return(false)
        post :create, {:vineyard => { "producer_id" => "invalid value" }}, valid_session
        assigns(:vineyard).should be_a_new(Vineyard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vineyard.any_instance.stub(:save).and_return(false)
        post :create, {:vineyard => { "producer_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vineyard" do
        vineyard = Vineyard.create! valid_attributes
        # Assuming there are no other vineyards in the database, this
        # specifies that the Vineyard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vineyard.any_instance.should_receive(:update_attributes).with({ "producer_id" => "1" })
        put :update, {:id => vineyard.to_param, :vineyard => { "producer_id" => "1" }}, valid_session
      end

      it "assigns the requested vineyard as @vineyard" do
        vineyard = Vineyard.create! valid_attributes
        put :update, {:id => vineyard.to_param, :vineyard => valid_attributes}, valid_session
        assigns(:vineyard).should eq(vineyard)
      end

      it "redirects to the vineyard" do
        vineyard = Vineyard.create! valid_attributes
        put :update, {:id => vineyard.to_param, :vineyard => valid_attributes}, valid_session
        response.should redirect_to(vineyard)
      end
    end

    describe "with invalid params" do
      it "assigns the vineyard as @vineyard" do
        vineyard = Vineyard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vineyard.any_instance.stub(:save).and_return(false)
        put :update, {:id => vineyard.to_param, :vineyard => { "producer_id" => "invalid value" }}, valid_session
        assigns(:vineyard).should eq(vineyard)
      end

      it "re-renders the 'edit' template" do
        vineyard = Vineyard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vineyard.any_instance.stub(:save).and_return(false)
        put :update, {:id => vineyard.to_param, :vineyard => { "producer_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vineyard" do
      vineyard = Vineyard.create! valid_attributes
      expect {
        delete :destroy, {:id => vineyard.to_param}, valid_session
      }.to change(Vineyard, :count).by(-1)
    end

    it "redirects to the vineyards list" do
      vineyard = Vineyard.create! valid_attributes
      delete :destroy, {:id => vineyard.to_param}, valid_session
      response.should redirect_to(vineyards_url)
    end
  end

end
