require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VineyardVintagesController do

  # This should return the minimal set of attributes required to create a valid
  # VineyardVintage. As you add validations to VineyardVintage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "vineyard_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VineyardVintagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vineyard_vintages as @vineyard_vintages" do
      vineyard_vintage = VineyardVintage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vineyard_vintages).should eq([vineyard_vintage])
    end
  end

  describe "GET show" do
    it "assigns the requested vineyard_vintage as @vineyard_vintage" do
      vineyard_vintage = VineyardVintage.create! valid_attributes
      get :show, {:id => vineyard_vintage.to_param}, valid_session
      assigns(:vineyard_vintage).should eq(vineyard_vintage)
    end
  end

  describe "GET new" do
    it "assigns a new vineyard_vintage as @vineyard_vintage" do
      get :new, {}, valid_session
      assigns(:vineyard_vintage).should be_a_new(VineyardVintage)
    end
  end

  describe "GET edit" do
    it "assigns the requested vineyard_vintage as @vineyard_vintage" do
      vineyard_vintage = VineyardVintage.create! valid_attributes
      get :edit, {:id => vineyard_vintage.to_param}, valid_session
      assigns(:vineyard_vintage).should eq(vineyard_vintage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VineyardVintage" do
        expect {
          post :create, {:vineyard_vintage => valid_attributes}, valid_session
        }.to change(VineyardVintage, :count).by(1)
      end

      it "assigns a newly created vineyard_vintage as @vineyard_vintage" do
        post :create, {:vineyard_vintage => valid_attributes}, valid_session
        assigns(:vineyard_vintage).should be_a(VineyardVintage)
        assigns(:vineyard_vintage).should be_persisted
      end

      it "redirects to the created vineyard_vintage" do
        post :create, {:vineyard_vintage => valid_attributes}, valid_session
        response.should redirect_to(VineyardVintage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vineyard_vintage as @vineyard_vintage" do
        # Trigger the behavior that occurs when invalid params are submitted
        VineyardVintage.any_instance.stub(:save).and_return(false)
        post :create, {:vineyard_vintage => { "vineyard_id" => "invalid value" }}, valid_session
        assigns(:vineyard_vintage).should be_a_new(VineyardVintage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VineyardVintage.any_instance.stub(:save).and_return(false)
        post :create, {:vineyard_vintage => { "vineyard_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vineyard_vintage" do
        vineyard_vintage = VineyardVintage.create! valid_attributes
        # Assuming there are no other vineyard_vintages in the database, this
        # specifies that the VineyardVintage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VineyardVintage.any_instance.should_receive(:update_attributes).with({ "vineyard_id" => "1" })
        put :update, {:id => vineyard_vintage.to_param, :vineyard_vintage => { "vineyard_id" => "1" }}, valid_session
      end

      it "assigns the requested vineyard_vintage as @vineyard_vintage" do
        vineyard_vintage = VineyardVintage.create! valid_attributes
        put :update, {:id => vineyard_vintage.to_param, :vineyard_vintage => valid_attributes}, valid_session
        assigns(:vineyard_vintage).should eq(vineyard_vintage)
      end

      it "redirects to the vineyard_vintage" do
        vineyard_vintage = VineyardVintage.create! valid_attributes
        put :update, {:id => vineyard_vintage.to_param, :vineyard_vintage => valid_attributes}, valid_session
        response.should redirect_to(vineyard_vintage)
      end
    end

    describe "with invalid params" do
      it "assigns the vineyard_vintage as @vineyard_vintage" do
        vineyard_vintage = VineyardVintage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VineyardVintage.any_instance.stub(:save).and_return(false)
        put :update, {:id => vineyard_vintage.to_param, :vineyard_vintage => { "vineyard_id" => "invalid value" }}, valid_session
        assigns(:vineyard_vintage).should eq(vineyard_vintage)
      end

      it "re-renders the 'edit' template" do
        vineyard_vintage = VineyardVintage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VineyardVintage.any_instance.stub(:save).and_return(false)
        put :update, {:id => vineyard_vintage.to_param, :vineyard_vintage => { "vineyard_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vineyard_vintage" do
      vineyard_vintage = VineyardVintage.create! valid_attributes
      expect {
        delete :destroy, {:id => vineyard_vintage.to_param}, valid_session
      }.to change(VineyardVintage, :count).by(-1)
    end

    it "redirects to the vineyard_vintages list" do
      vineyard_vintage = VineyardVintage.create! valid_attributes
      delete :destroy, {:id => vineyard_vintage.to_param}, valid_session
      response.should redirect_to(vineyard_vintages_url)
    end
  end

end
